name: summernote_richtextbox
description: A Flutter package that provides a rich text editor using Summernote with WebView integration for Windows desktop applications.
version: 1.0.0
homepage: https://github.com/fahimShahriaar/summernote_richtextbox_windows
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/summernote.html
    - assets/css/bootstrap.min.css
    - assets/css/bootstrap-icons.min.css
    - assets/css/summernote-bs5.min.css
    - assets/fonts/bootstrap-icons.woff
    - assets/fonts/bootstrap-icons.woff2
    - assets/fonts/summernote.eot
    - assets/fonts/summernote.ttf
    - assets/js/bootstrap.bundle.min.js
    - assets/js/jquery.min.js
    - assets/js/summernote-bs5.min.js
    - assets/fonts/
    - assets/css/
    - assets/js/
